// app-react/containers/batch-upload/index.js
import React, { PropTypes } from 'react';
import { bindActionCreators } from 'redux';
import { connect } from 'react-redux';
import BatchUpload from '../../components/batch-upload';
import appState from '../../state';
import orderOps from '../../lib/order-ops';
import Async from 'async';

const container = ( { state, updateBatch } ) => {
	const handleResult = ( error, data ) => {
		if ( error ) {
			return updateBatch( { error } );
		}

		updateBatch( Object.assign( {}, data, { status: 'stats' } ) );
	};

	const refresh = () => {
		updateBatch( { status: 'loading' } );
		orderOps.orderStats( handleResult );
	};

	const clearAll = () => {
		updateBatch( { status: 'loading' } );
		orderOps.clearAll( handleResult );
	};

	const backfillOrder = ( orderId, callback ) => {
		updateBatch( {
			status: 'backfill',
			orderId,
		} );

		orderOps.backfill( orderId, callback );
	};

	const backfill = () => {
		updateBatch( { status: 'loading' } );
		Async.eachSeries( state.notBackfilled, backfillOrder, ( error ) => {
			if ( error ) {
				return updateBatch( { error } );
			}

			refresh();
		} )
	};

	return <BatchUpload { ...state } { ...{ refresh, clearAll, backfill } }/>;
};

container.propTypes = {
	state: PropTypes.object.isRequired,
	updateBatch: PropTypes.func.isRequired,
};

function mapStateToProps( state ) {
	return {
		state: state.batch,
	};
}

function mapDispatchToProps( dispatch ) {
	return {
		updateBatch: bindActionCreators( appState.actions, dispatch ).updateBatch,
	};
}

export default connect(
	mapStateToProps,
	mapDispatchToProps
)( container );

// app/BatchUpload.vue
<template>
    <div>
        <button type="button" className="button-primary" @click="clearAll">Clear Data</button>
        <button type="button" className="button-primary" @click="backfill">Back-Fill</button>
        <button type="button" className="button-primary" @click="refresh">Refresh</button>

        <p v-if="status == 'error'">{{ error.toString() }}:{{ error.text }}</p>;
        <p v-if="status == 'loading'">Loading...</p>
        <p v-if="status == 'backfill'">Backfilling order #{{ orderId }}</p>
		<p v-if="status == 'stats'">
			Orders: {{ totalOrders }} <br />
			Backfilled: {{ numBackfilled }} <br />
			Not Backfilled: {{ numNotBackfilled }}
		</p>
    </div>
</template>

<script>
import orders from './lib/order-ops'
import orderOps from './lib/order-ops';

export default {
    name: 'BatchUpload',
    props: {
        notBackfilled: Array,
        backfilled: Array,
    },
    data () { return { 
        error: null,
        status: 'loading',
        orderId: '',
    } },
    computed: {
        totalOrders () { return this.notBackfilled.length + this.backfilled.length },
        numBackfilled () { return this.backfilled.length },
        numNotBackfilled () { return this.notBackfilled.length },
    },
    methods: {
        handleError(error) {
            this.status = 'error'
            this.error = error
        },
        clearAll() { console.log('clearAll clicked') },
        async backfill() { 
            try {
                this.status = 'backfill'
                for (let i = 0; i < this.notBackfilled.length; i++) {
                    const id = this.notBackfilled[i]
                    this.orderId = id
                    const data = await orderOps.backfill(id)
                    Object.assign(this, data)
                }
            } catch (error) {
                this.handleError(error)
            }
         },
        refresh() {
            orders.orderStats() 
                .then((data) => {
                    this.status = 'stats'
                    Object.assign(this, data)
                })
                .catch(this.handleError)
        },
    },
}
</script>
