// app-react/components/order-control/index.js
import React, { PropTypes } from 'react';
import settings from '../../lib/settings';

const divStyle = {
	width: '24px',
	display: 'block',
	float: 'none',
};

const Icon = ( { imgUrl, alt, onClick, title } ) => {
	return (
		<div title={ title } id="siftsci_icon" className="siftsci_icon" style={ divStyle } onClick={ onClick } >
			<img src={ imgUrl } alt={ alt } width="20px" height="20px" />
		</div>
	);
};

const scoreStyle = {
	color: 'white',
	textAlign: 'center',
	border: '1px solid black',
	width: '20px',
	height: '20px',
	margin: '0px',
};

const getColor = ( score ) => {
	const thresholdBad = settings.thresholdBad || 60;
	if ( thresholdBad <= score ) {
		return 'red';
	}

	const thresholdGood = settings.thresholdGood || 30;
	if ( thresholdGood >= score ) {
		return 'green';
	}

	return 'orange';
};

const Score = ( { score, openSiftSci } ) => {
	const style = Object.assign( {}, scoreStyle, {
		backgroundColor: getColor( score ),
	} );

	const title = "The user's SiftScience score";

	return (
		<div title={ title } id="siftsci_score" className="siftsci_score" style={ divStyle } onClick={ openSiftSci }>
			<div style={ style }>{ score }</div>
		</div>
	);
};

const LabelButton = ( { type, label, imgPath, setLabel } ) => {
	const isSet = type === label;
	const title = isSet ? 'Click to remove this label' : 'Click to set this label';
	const image = type + ( isSet ? '.png' : '-gray.png' );
	const callback = () => setLabel( isSet ? null : type );
	return (
		<Icon title={ title } imgUrl={ imgPath + image } alt={ type } onClick={ callback } />
	);
};

const control = ( props ) => {
	const { error, isWorking, isBackfilled, score, imgPath, uploadOrder } = props;
	if ( error ) {
		console.log( 'error: ', error );
		return <Icon imgUrl={ imgPath + 'error.png' } alt="error" />;
	}

	if ( isWorking ) {
		return <Icon imgUrl={ imgPath + 'spinner.gif' } alt="working" />;
	}

	if ( isBackfilled && score ) {
		return (
			<div>
				<Score { ...props } />
				<LabelButton { ...props } type="good" />
				<LabelButton { ...props } type="bad" />
			</div>
		);
	}

	return <Icon imgUrl={ imgPath + 'upload.png' } alt="upload" onClick={ uploadOrder } />;
};

control.propTypes = {
	error: PropTypes.string,
	isWorking: PropTypes.bool.isRequired,
	isBackfilled: PropTypes.bool,
	score: PropTypes.number,
	label: PropTypes.string,
	imgPath: PropTypes.string.isRequired,
	openSiftSci: PropTypes.func.isRequired,
	setLabel: PropTypes.func.isRequired,
	uploadOrder: PropTypes.func.isRequired,
};

export default control;

// app/OrderControl.vue
<template>
    <div>
        <div v-if="error" :style="iconStyle">
            <img :src="errorImage" :alt="error" width="20px" height="20px" />
        </div>    
        
        <div v-if="isLoading" :style="iconStyle">
            <img :src="spinnerImage" alt="Working..." width="20px" height="20px" />
        </div>    
        
        <div v-if="noData" :style="iconStyle" @click="backfill($event)">
            <img :src="uploadImage" alt="Working..." width="20px" height="20px" />
        </div>    
        
        <div v-if="hasData">
            <div title="User's Sift score" :style="scoreStyle" @click="openSiftSci($event)">
                <div :style="{ backgroundColor: scoreColor }">{{ score }}</div>
            </div>

            <div :title="goodTitle" :style="iconStyle" @click="clickGood">
                <img :src="goodImage" alt="good" width="20px" height="20px" />
            </div>    
        
            <div :title="goodTitle" :style="iconStyle" @click="clickBad">
                <img :src="badImage" alt="bad" width="20px" height="20px" />
            </div>    
        </div>
    </div>
</template>

<script>
import {getSettings, getLabel, setLabel, extractScore, extractLabel, backfill} from './api';
import {iconStyle, scoreStyle, getColor} from './styles';

export default {
    name: 'OrderControl',
    props: { id: String },
    created() { this.refresh() },
    data () {
        return {
            iconStyle, 
            scoreStyle: Object.assign({}, scoreStyle),
            state: 'loading',
            error: null,
            isBackfilled: false,
            score: 0,
            label: null,
            user_id: null,
        }
    },
    computed: {
        isLoading () { return this.state === 'loading' },
        errorImage() { return this.getImage('error.png') },
        spinnerImage() { return this.getImage('spinner.gif') },
        uploadImage() { return this.getImage('upload.png') },
        hasData () { return this.state === 'data' },
        noData () { return this.state === 'nodata' },
        goodTitle () { return this.getTitle('good') },
        badTitle () { return this.getTitle('bad') },
        goodImage () { return this.getLabelImage('good') },
        badImage () { return this.getLabelImage('bad') },
    },
    methods: {
        clickGood(e) { this.setLabel('good', e) },
        clickBad(e) { this.setLabel('bad', e) },
        getTitle(v) { return v === this.label ? 'Click to remove this label' : 'Click to set this label'},
        openSiftSci (e) { 
            e.preventDefault()
            e.stopPropagation()
            window.open('https://siftscience.com/console/users/' + this.userId) 
        },
        getLabelImage(v) {
            const ending = v === this.label ? '.png' : '-gray.png'
            return this.getImage(v + ending)
        },
        getImage(file) {
            return getSettings().imgPath + file
        },
        async setLabel(v, e) {
            e.preventDefault()
            e.stopPropagation()
            this.error = null
            this.state = 'loading'
            await setLabel(this.id, v === this.label ? null : v)
            await this.refresh()
        },
        async backfill(e) {
            e.preventDefault()
            e.stopPropagation()
            this.error = null
            this.state = 'loading'   
            await backfill(this.id)
            await this.refresh()        
        },
        async refresh() {
            try {
                this.error = null
                this.state = 'loading'
                const data = await getLabel(this.id)
                this.userId = data.sift.user_id
                this.score = extractScore(data.sift)
                this.label = extractLabel(data.sift)
                this.scoreStyle.backgroundColor = getColor(this.score)
                this.isBackfilled = data.is_backfilled
                const hasData = this.isBackfilled && this.score
                this.state = hasData ? 'data' : 'nodata'
            } catch (error) {
                this.error = error
                this.state = 'error';
            }
        },
    } 
}
</script>
